// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin_logout.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AdminLogoutRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminLogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminLogoutRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminLogoutRequestMultiError, or nil if none found.
func (m *AdminLogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminLogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AdminLogoutRequestMultiError(errors)
	}

	return nil
}

// AdminLogoutRequestMultiError is an error wrapping multiple validation errors
// returned by AdminLogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type AdminLogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminLogoutRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminLogoutRequestMultiError) AllErrors() []error { return m }

// AdminLogoutRequestValidationError is the validation error returned by
// AdminLogoutRequest.Validate if the designated constraints aren't met.
type AdminLogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminLogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminLogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminLogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminLogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminLogoutRequestValidationError) ErrorName() string {
	return "AdminLogoutRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AdminLogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminLogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminLogoutRequestValidationError{}

// Validate checks the field values on AdminLogoutResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminLogoutResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminLogoutResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminLogoutResponseMultiError, or nil if none found.
func (m *AdminLogoutResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminLogoutResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AdminLogoutResponseMultiError(errors)
	}

	return nil
}

// AdminLogoutResponseMultiError is an error wrapping multiple validation
// errors returned by AdminLogoutResponse.ValidateAll() if the designated
// constraints aren't met.
type AdminLogoutResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminLogoutResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminLogoutResponseMultiError) AllErrors() []error { return m }

// AdminLogoutResponseValidationError is the validation error returned by
// AdminLogoutResponse.Validate if the designated constraints aren't met.
type AdminLogoutResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminLogoutResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminLogoutResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminLogoutResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminLogoutResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminLogoutResponseValidationError) ErrorName() string {
	return "AdminLogoutResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AdminLogoutResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminLogoutResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminLogoutResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminLogoutResponseValidationError{}
