// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AdminLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AdminLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminLoginRequestMultiError, or nil if none found.
func (m *AdminLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserName

	// no validation rules for Password

	if len(errors) > 0 {
		return AdminLoginRequestMultiError(errors)
	}

	return nil
}

// AdminLoginRequestMultiError is an error wrapping multiple validation errors
// returned by AdminLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type AdminLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminLoginRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminLoginRequestMultiError) AllErrors() []error { return m }

// AdminLoginRequestValidationError is the validation error returned by
// AdminLoginRequest.Validate if the designated constraints aren't met.
type AdminLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminLoginRequestValidationError) ErrorName() string {
	return "AdminLoginRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AdminLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminLoginRequestValidationError{}

// Validate checks the field values on AdminLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AdminLoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AdminLoginResponseMultiError, or nil if none found.
func (m *AdminLoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminLoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for AccessToken

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return AdminLoginResponseMultiError(errors)
	}

	return nil
}

// AdminLoginResponseMultiError is an error wrapping multiple validation errors
// returned by AdminLoginResponse.ValidateAll() if the designated constraints
// aren't met.
type AdminLoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminLoginResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminLoginResponseMultiError) AllErrors() []error { return m }

// AdminLoginResponseValidationError is the validation error returned by
// AdminLoginResponse.Validate if the designated constraints aren't met.
type AdminLoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminLoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminLoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminLoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminLoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminLoginResponseValidationError) ErrorName() string {
	return "AdminLoginResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AdminLoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminLoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminLoginResponseValidationError{}
