app:
  env: dev
  run_mode: debug

server:
  http: 8080
  websocket: 8081
  tcp: 8082

log:
  path: "./temp"

mysql:
  host: 59.110.137.58
  port: 3307
  username: root
  password: xin1223
  dbname: c_program_edu
  parameters: "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

redis:
  host: 59.110.137.58
  port: 6379
  auth: xin1223
  database: 0

jwt:
  secret: 836c3fea9bba4e04d51bd0fbcc5
  expires_time: 604800
  buffer_time: 3600

email:
  host: smtp.163.com
  smtp: smtp.163.com:25
  addr: tich0425@163.com
  name: test
  password: FLBUHLEVTPDMLUWY
  expires: 10

file_system:
  default: local
  local:
    # 文件保存的根目录
    root: "temp/uploads/"
    # 公开的 bucket
    bucket_public: "public"
    # 私有的 bucket
    bucket_private: "private"
    endpoint: "http://localhost:8080"
    ssl: false