// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: add_question.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddQuestionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddQuestionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddQuestionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddQuestionRequestMultiError, or nil if none found.
func (m *AddQuestionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddQuestionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Answer

	// no validation rules for Degree

	// no validation rules for Status

	if len(errors) > 0 {
		return AddQuestionRequestMultiError(errors)
	}

	return nil
}

// AddQuestionRequestMultiError is an error wrapping multiple validation errors
// returned by AddQuestionRequest.ValidateAll() if the designated constraints
// aren't met.
type AddQuestionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddQuestionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddQuestionRequestMultiError) AllErrors() []error { return m }

// AddQuestionRequestValidationError is the validation error returned by
// AddQuestionRequest.Validate if the designated constraints aren't met.
type AddQuestionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddQuestionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddQuestionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddQuestionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddQuestionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddQuestionRequestValidationError) ErrorName() string {
	return "AddQuestionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddQuestionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddQuestionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddQuestionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddQuestionRequestValidationError{}

// Validate checks the field values on AddQuestionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddQuestionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddQuestionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddQuestionResponseMultiError, or nil if none found.
func (m *AddQuestionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddQuestionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddQuestionResponseMultiError(errors)
	}

	return nil
}

// AddQuestionResponseMultiError is an error wrapping multiple validation
// errors returned by AddQuestionResponse.ValidateAll() if the designated
// constraints aren't met.
type AddQuestionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddQuestionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddQuestionResponseMultiError) AllErrors() []error { return m }

// AddQuestionResponseValidationError is the validation error returned by
// AddQuestionResponse.Validate if the designated constraints aren't met.
type AddQuestionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddQuestionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddQuestionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddQuestionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddQuestionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddQuestionResponseValidationError) ErrorName() string {
	return "AddQuestionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddQuestionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddQuestionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddQuestionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddQuestionResponseValidationError{}

// Validate checks the field values on AddTestDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddTestDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTestDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddTestDataRequestMultiError, or nil if none found.
func (m *AddTestDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTestDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for QuestionId

	// no validation rules for Input

	// no validation rules for Output

	if len(errors) > 0 {
		return AddTestDataRequestMultiError(errors)
	}

	return nil
}

// AddTestDataRequestMultiError is an error wrapping multiple validation errors
// returned by AddTestDataRequest.ValidateAll() if the designated constraints
// aren't met.
type AddTestDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTestDataRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTestDataRequestMultiError) AllErrors() []error { return m }

// AddTestDataRequestValidationError is the validation error returned by
// AddTestDataRequest.Validate if the designated constraints aren't met.
type AddTestDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTestDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTestDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTestDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTestDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTestDataRequestValidationError) ErrorName() string {
	return "AddTestDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddTestDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTestDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTestDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTestDataRequestValidationError{}

// Validate checks the field values on AddTestDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddTestDataResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTestDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddTestDataResponseMultiError, or nil if none found.
func (m *AddTestDataResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTestDataResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddTestDataResponseMultiError(errors)
	}

	return nil
}

// AddTestDataResponseMultiError is an error wrapping multiple validation
// errors returned by AddTestDataResponse.ValidateAll() if the designated
// constraints aren't met.
type AddTestDataResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTestDataResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTestDataResponseMultiError) AllErrors() []error { return m }

// AddTestDataResponseValidationError is the validation error returned by
// AddTestDataResponse.Validate if the designated constraints aren't met.
type AddTestDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTestDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTestDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTestDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTestDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTestDataResponseValidationError) ErrorName() string {
	return "AddTestDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddTestDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTestDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTestDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTestDataResponseValidationError{}
