// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: test_data.proto

package admin

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTestDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId int32 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty" form:"question_id"`
}

func (x *GetTestDataRequest) Reset() {
	*x = GetTestDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestDataRequest) ProtoMessage() {}

func (x *GetTestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestDataRequest.ProtoReflect.Descriptor instead.
func (*GetTestDataRequest) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetTestDataRequest) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type GetTestDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestDataList []*GetTestDataResponse_TestDataItem `protobuf:"bytes,1,rep,name=test_data_list,json=testDataList,proto3" json:"test_data_list,omitempty" binding:"required"`
}

func (x *GetTestDataResponse) Reset() {
	*x = GetTestDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestDataResponse) ProtoMessage() {}

func (x *GetTestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestDataResponse.ProtoReflect.Descriptor instead.
func (*GetTestDataResponse) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetTestDataResponse) GetTestDataList() []*GetTestDataResponse_TestDataItem {
	if x != nil {
		return x.TestDataList
	}
	return nil
}

type UpdateTestDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	Input  string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty" binding:"required"`
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty" binding:"required"`
}

func (x *UpdateTestDataRequest) Reset() {
	*x = UpdateTestDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTestDataRequest) ProtoMessage() {}

func (x *UpdateTestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTestDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateTestDataRequest) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTestDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTestDataRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *UpdateTestDataRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type UpdateTestDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateTestDataResponse) Reset() {
	*x = UpdateTestDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTestDataResponse) ProtoMessage() {}

func (x *UpdateTestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTestDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateTestDataResponse) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{3}
}

type DeleteTestDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id"`
}

func (x *DeleteTestDataRequest) Reset() {
	*x = DeleteTestDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTestDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTestDataRequest) ProtoMessage() {}

func (x *DeleteTestDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTestDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteTestDataRequest) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTestDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTestDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTestDataResponse) Reset() {
	*x = DeleteTestDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTestDataResponse) ProtoMessage() {}

func (x *DeleteTestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTestDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteTestDataResponse) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{5}
}

type GetTestDataResponse_TestDataItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	Input      string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty" binding:"required"`
	Output     string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty" binding:"required"`
	QuestionId int32  `protobuf:"varint,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty" binding:"required"`
}

func (x *GetTestDataResponse_TestDataItem) Reset() {
	*x = GetTestDataResponse_TestDataItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTestDataResponse_TestDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestDataResponse_TestDataItem) ProtoMessage() {}

func (x *GetTestDataResponse_TestDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_test_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestDataResponse_TestDataItem.ProtoReflect.Descriptor instead.
func (*GetTestDataResponse_TestDataItem) Descriptor() ([]byte, []int) {
	return file_test_data_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetTestDataResponse_TestDataItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTestDataResponse_TestDataItem) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *GetTestDataResponse_TestDataItem) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetTestDataResponse_TestDataItem) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

var File_test_data_proto protoreflect.FileDescriptor

var file_test_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x1f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x74, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x67,
	0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x38, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x66, 0x6f, 0x72, 0x6d, 0x3a,
	0x22, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xd1, 0x02, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x66, 0x0a, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74,
	0x65, 0x6d, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x0c, 0x74, 0x65, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0xd1, 0x01, 0x0a, 0x0c, 0x54, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x22, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xa0, 0x01,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x2f, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x15, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x0e, 0x9a, 0x84, 0x9e, 0x03, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x69, 0x64, 0x22, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x65, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a,
	0x17, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_data_proto_rawDescOnce sync.Once
	file_test_data_proto_rawDescData = file_test_data_proto_rawDesc
)

func file_test_data_proto_rawDescGZIP() []byte {
	file_test_data_proto_rawDescOnce.Do(func() {
		file_test_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_data_proto_rawDescData)
	})
	return file_test_data_proto_rawDescData
}

var file_test_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_test_data_proto_goTypes = []interface{}{
	(*GetTestDataRequest)(nil),               // 0: admin.GetTestDataRequest
	(*GetTestDataResponse)(nil),              // 1: admin.GetTestDataResponse
	(*UpdateTestDataRequest)(nil),            // 2: admin.UpdateTestDataRequest
	(*UpdateTestDataResponse)(nil),           // 3: admin.UpdateTestDataResponse
	(*DeleteTestDataRequest)(nil),            // 4: admin.DeleteTestDataRequest
	(*DeleteTestDataResponse)(nil),           // 5: admin.DeleteTestDataResponse
	(*GetTestDataResponse_TestDataItem)(nil), // 6: admin.GetTestDataResponse.TestDataItem
}
var file_test_data_proto_depIdxs = []int32{
	6, // 0: admin.GetTestDataResponse.test_data_list:type_name -> admin.GetTestDataResponse.TestDataItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_test_data_proto_init() }
func file_test_data_proto_init() {
	if File_test_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTestDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTestDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTestDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTestDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTestDataResponse_TestDataItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_data_proto_goTypes,
		DependencyIndexes: file_test_data_proto_depIdxs,
		MessageInfos:      file_test_data_proto_msgTypes,
	}.Build()
	File_test_data_proto = out.File
	file_test_data_proto_rawDesc = nil
	file_test_data_proto_goTypes = nil
	file_test_data_proto_depIdxs = nil
}
