// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tag_delete.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeleteTagRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteTagRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTagRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTagRequestMultiError, or nil if none found.
func (m *DeleteTagRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTagRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteTagRequestMultiError(errors)
	}

	return nil
}

// DeleteTagRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteTagRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteTagRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTagRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTagRequestMultiError) AllErrors() []error { return m }

// DeleteTagRequestValidationError is the validation error returned by
// DeleteTagRequest.Validate if the designated constraints aren't met.
type DeleteTagRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTagRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTagRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTagRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTagRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTagRequestValidationError) ErrorName() string { return "DeleteTagRequestValidationError" }

// Error satisfies the builtin error interface
func (e DeleteTagRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTagRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTagRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTagRequestValidationError{}

// Validate checks the field values on DeleteTagResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteTagResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTagResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTagResponseMultiError, or nil if none found.
func (m *DeleteTagResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTagResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTagResponseMultiError(errors)
	}

	return nil
}

// DeleteTagResponseMultiError is an error wrapping multiple validation errors
// returned by DeleteTagResponse.ValidateAll() if the designated constraints
// aren't met.
type DeleteTagResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTagResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTagResponseMultiError) AllErrors() []error { return m }

// DeleteTagResponseValidationError is the validation error returned by
// DeleteTagResponse.Validate if the designated constraints aren't met.
type DeleteTagResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTagResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTagResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTagResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTagResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTagResponseValidationError) ErrorName() string {
	return "DeleteTagResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTagResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTagResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTagResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTagResponseValidationError{}
