// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tag_update.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TagUpdateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TagUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TagUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TagUpdateRequestMultiError, or nil if none found.
func (m *TagUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TagUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return TagUpdateRequestMultiError(errors)
	}

	return nil
}

// TagUpdateRequestMultiError is an error wrapping multiple validation errors
// returned by TagUpdateRequest.ValidateAll() if the designated constraints
// aren't met.
type TagUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagUpdateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagUpdateRequestMultiError) AllErrors() []error { return m }

// TagUpdateRequestValidationError is the validation error returned by
// TagUpdateRequest.Validate if the designated constraints aren't met.
type TagUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagUpdateRequestValidationError) ErrorName() string { return "TagUpdateRequestValidationError" }

// Error satisfies the builtin error interface
func (e TagUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagUpdateRequestValidationError{}

// Validate checks the field values on TagUpdateResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TagUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TagUpdateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TagUpdateResponseMultiError, or nil if none found.
func (m *TagUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TagUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TagUpdateResponseMultiError(errors)
	}

	return nil
}

// TagUpdateResponseMultiError is an error wrapping multiple validation errors
// returned by TagUpdateResponse.ValidateAll() if the designated constraints
// aren't met.
type TagUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagUpdateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagUpdateResponseMultiError) AllErrors() []error { return m }

// TagUpdateResponseValidationError is the validation error returned by
// TagUpdateResponse.Validate if the designated constraints aren't met.
type TagUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagUpdateResponseValidationError) ErrorName() string {
	return "TagUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TagUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagUpdateResponseValidationError{}
