// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tag_add.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddTagRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddTagRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTagRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddTagRequestMultiError, or
// nil if none found.
func (m *AddTagRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTagRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return AddTagRequestMultiError(errors)
	}

	return nil
}

// AddTagRequestMultiError is an error wrapping multiple validation errors
// returned by AddTagRequest.ValidateAll() if the designated constraints
// aren't met.
type AddTagRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTagRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTagRequestMultiError) AllErrors() []error { return m }

// AddTagRequestValidationError is the validation error returned by
// AddTagRequest.Validate if the designated constraints aren't met.
type AddTagRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTagRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTagRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTagRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTagRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTagRequestValidationError) ErrorName() string { return "AddTagRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddTagRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTagRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTagRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTagRequestValidationError{}

// Validate checks the field values on AddTagResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddTagResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddTagResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddTagResponseMultiError,
// or nil if none found.
func (m *AddTagResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddTagResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddTagResponseMultiError(errors)
	}

	return nil
}

// AddTagResponseMultiError is an error wrapping multiple validation errors
// returned by AddTagResponse.ValidateAll() if the designated constraints
// aren't met.
type AddTagResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddTagResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddTagResponseMultiError) AllErrors() []error { return m }

// AddTagResponseValidationError is the validation error returned by
// AddTagResponse.Validate if the designated constraints aren't met.
type AddTagResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddTagResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddTagResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddTagResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddTagResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddTagResponseValidationError) ErrorName() string { return "AddTagResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddTagResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddTagResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddTagResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddTagResponseValidationError{}
