// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tag_list.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TagListRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TagListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TagListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TagListRequestMultiError,
// or nil if none found.
func (m *TagListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TagListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Search

	// no validation rules for Page

	// no validation rules for Number

	if len(errors) > 0 {
		return TagListRequestMultiError(errors)
	}

	return nil
}

// TagListRequestMultiError is an error wrapping multiple validation errors
// returned by TagListRequest.ValidateAll() if the designated constraints
// aren't met.
type TagListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagListRequestMultiError) AllErrors() []error { return m }

// TagListRequestValidationError is the validation error returned by
// TagListRequest.Validate if the designated constraints aren't met.
type TagListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagListRequestValidationError) ErrorName() string { return "TagListRequestValidationError" }

// Error satisfies the builtin error interface
func (e TagListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagListRequestValidationError{}

// Validate checks the field values on TagListResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TagListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TagListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TagListResponseMultiError, or nil if none found.
func (m *TagListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TagListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTagList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TagListResponseValidationError{
						field:  fmt.Sprintf("TagList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TagListResponseValidationError{
						field:  fmt.Sprintf("TagList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TagListResponseValidationError{
					field:  fmt.Sprintf("TagList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return TagListResponseMultiError(errors)
	}

	return nil
}

// TagListResponseMultiError is an error wrapping multiple validation errors
// returned by TagListResponse.ValidateAll() if the designated constraints
// aren't met.
type TagListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagListResponseMultiError) AllErrors() []error { return m }

// TagListResponseValidationError is the validation error returned by
// TagListResponse.Validate if the designated constraints aren't met.
type TagListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagListResponseValidationError) ErrorName() string { return "TagListResponseValidationError" }

// Error satisfies the builtin error interface
func (e TagListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagListResponseValidationError{}

// Validate checks the field values on TagListResponse_TagItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TagListResponse_TagItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TagListResponse_TagItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TagListResponse_TagItemMultiError, or nil if none found.
func (m *TagListResponse_TagItem) ValidateAll() error {
	return m.validate(true)
}

func (m *TagListResponse_TagItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Count

	if len(errors) > 0 {
		return TagListResponse_TagItemMultiError(errors)
	}

	return nil
}

// TagListResponse_TagItemMultiError is an error wrapping multiple validation
// errors returned by TagListResponse_TagItem.ValidateAll() if the designated
// constraints aren't met.
type TagListResponse_TagItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagListResponse_TagItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagListResponse_TagItemMultiError) AllErrors() []error { return m }

// TagListResponse_TagItemValidationError is the validation error returned by
// TagListResponse_TagItem.Validate if the designated constraints aren't met.
type TagListResponse_TagItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagListResponse_TagItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagListResponse_TagItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagListResponse_TagItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagListResponse_TagItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagListResponse_TagItemValidationError) ErrorName() string {
	return "TagListResponse_TagItemValidationError"
}

// Error satisfies the builtin error interface
func (e TagListResponse_TagItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTagListResponse_TagItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagListResponse_TagItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagListResponse_TagItemValidationError{}
