// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: delete_admin.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeleteAdminRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAdminRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAdminRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteAdminRequestMultiError, or nil if none found.
func (m *DeleteAdminRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAdminRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteAdminRequestMultiError(errors)
	}

	return nil
}

// DeleteAdminRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteAdminRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteAdminRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAdminRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAdminRequestMultiError) AllErrors() []error { return m }

// DeleteAdminRequestValidationError is the validation error returned by
// DeleteAdminRequest.Validate if the designated constraints aren't met.
type DeleteAdminRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAdminRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAdminRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAdminRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAdminRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAdminRequestValidationError) ErrorName() string {
	return "DeleteAdminRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAdminRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAdminRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAdminRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAdminRequestValidationError{}

// Validate checks the field values on DeleteAdminResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAdminResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAdminResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteAdminResponseMultiError, or nil if none found.
func (m *DeleteAdminResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAdminResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteAdminResponseMultiError(errors)
	}

	return nil
}

// DeleteAdminResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteAdminResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteAdminResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAdminResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAdminResponseMultiError) AllErrors() []error { return m }

// DeleteAdminResponseValidationError is the validation error returned by
// DeleteAdminResponse.Validate if the designated constraints aren't met.
type DeleteAdminResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAdminResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAdminResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAdminResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAdminResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAdminResponseValidationError) ErrorName() string {
	return "DeleteAdminResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAdminResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAdminResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAdminResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAdminResponseValidationError{}
