// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: get_all_bank.proto

package web

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetAllBankRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAllBankRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllBankRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllBankRequestMultiError, or nil if none found.
func (m *GetAllBankRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllBankRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Grade

	if len(errors) > 0 {
		return GetAllBankRequestMultiError(errors)
	}

	return nil
}

// GetAllBankRequestMultiError is an error wrapping multiple validation errors
// returned by GetAllBankRequest.ValidateAll() if the designated constraints
// aren't met.
type GetAllBankRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllBankRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllBankRequestMultiError) AllErrors() []error { return m }

// GetAllBankRequestValidationError is the validation error returned by
// GetAllBankRequest.Validate if the designated constraints aren't met.
type GetAllBankRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllBankRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllBankRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllBankRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllBankRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllBankRequestValidationError) ErrorName() string {
	return "GetAllBankRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllBankRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllBankRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllBankRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllBankRequestValidationError{}

// Validate checks the field values on GetAllBankResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllBankResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllBankResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllBankResponseMultiError, or nil if none found.
func (m *GetAllBankResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllBankResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBankList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAllBankResponseValidationError{
						field:  fmt.Sprintf("BankList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAllBankResponseValidationError{
						field:  fmt.Sprintf("BankList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAllBankResponseValidationError{
					field:  fmt.Sprintf("BankList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAllBankResponseMultiError(errors)
	}

	return nil
}

// GetAllBankResponseMultiError is an error wrapping multiple validation errors
// returned by GetAllBankResponse.ValidateAll() if the designated constraints
// aren't met.
type GetAllBankResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllBankResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllBankResponseMultiError) AllErrors() []error { return m }

// GetAllBankResponseValidationError is the validation error returned by
// GetAllBankResponse.Validate if the designated constraints aren't met.
type GetAllBankResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllBankResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllBankResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllBankResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllBankResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllBankResponseValidationError) ErrorName() string {
	return "GetAllBankResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllBankResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllBankResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllBankResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllBankResponseValidationError{}

// Validate checks the field values on GetAllBankResponse_BankItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllBankResponse_BankItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllBankResponse_BankItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllBankResponse_BankItemMultiError, or nil if none found.
func (m *GetAllBankResponse_BankItem) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllBankResponse_BankItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Content

	// no validation rules for Participants

	// no validation rules for Completed

	// no validation rules for Count

	if len(errors) > 0 {
		return GetAllBankResponse_BankItemMultiError(errors)
	}

	return nil
}

// GetAllBankResponse_BankItemMultiError is an error wrapping multiple
// validation errors returned by GetAllBankResponse_BankItem.ValidateAll() if
// the designated constraints aren't met.
type GetAllBankResponse_BankItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllBankResponse_BankItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllBankResponse_BankItemMultiError) AllErrors() []error { return m }

// GetAllBankResponse_BankItemValidationError is the validation error returned
// by GetAllBankResponse_BankItem.Validate if the designated constraints
// aren't met.
type GetAllBankResponse_BankItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllBankResponse_BankItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllBankResponse_BankItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllBankResponse_BankItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllBankResponse_BankItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllBankResponse_BankItemValidationError) ErrorName() string {
	return "GetAllBankResponse_BankItemValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllBankResponse_BankItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllBankResponse_BankItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllBankResponse_BankItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllBankResponse_BankItemValidationError{}
