// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"c_program_edu-gin/internal/app/api"
	"c_program_edu-gin/internal/config"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *api.AppProvider {
	appProvider := &api.AppProvider{
		Config: conf,
	}
	return appProvider
}
