// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: competition_list.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CompetitionListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CompetitionListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CompetitionListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CompetitionListRequestMultiError, or nil if none found.
func (m *CompetitionListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CompetitionListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Number

	// no validation rules for Search

	if len(errors) > 0 {
		return CompetitionListRequestMultiError(errors)
	}

	return nil
}

// CompetitionListRequestMultiError is an error wrapping multiple validation
// errors returned by CompetitionListRequest.ValidateAll() if the designated
// constraints aren't met.
type CompetitionListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompetitionListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompetitionListRequestMultiError) AllErrors() []error { return m }

// CompetitionListRequestValidationError is the validation error returned by
// CompetitionListRequest.Validate if the designated constraints aren't met.
type CompetitionListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompetitionListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompetitionListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompetitionListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompetitionListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompetitionListRequestValidationError) ErrorName() string {
	return "CompetitionListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CompetitionListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompetitionListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompetitionListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompetitionListRequestValidationError{}

// Validate checks the field values on CompetitionListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CompetitionListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CompetitionListResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CompetitionListResponseMultiError, or nil if none found.
func (m *CompetitionListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CompetitionListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCompetitionList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CompetitionListResponseValidationError{
						field:  fmt.Sprintf("CompetitionList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CompetitionListResponseValidationError{
						field:  fmt.Sprintf("CompetitionList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CompetitionListResponseValidationError{
					field:  fmt.Sprintf("CompetitionList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return CompetitionListResponseMultiError(errors)
	}

	return nil
}

// CompetitionListResponseMultiError is an error wrapping multiple validation
// errors returned by CompetitionListResponse.ValidateAll() if the designated
// constraints aren't met.
type CompetitionListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompetitionListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompetitionListResponseMultiError) AllErrors() []error { return m }

// CompetitionListResponseValidationError is the validation error returned by
// CompetitionListResponse.Validate if the designated constraints aren't met.
type CompetitionListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompetitionListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompetitionListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompetitionListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompetitionListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompetitionListResponseValidationError) ErrorName() string {
	return "CompetitionListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CompetitionListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompetitionListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompetitionListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompetitionListResponseValidationError{}

// Validate checks the field values on CompetitionListResponse_CompetitionItem
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *CompetitionListResponse_CompetitionItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// CompetitionListResponse_CompetitionItem with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// CompetitionListResponse_CompetitionItemMultiError, or nil if none found.
func (m *CompetitionListResponse_CompetitionItem) ValidateAll() error {
	return m.validate(true)
}

func (m *CompetitionListResponse_CompetitionItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for OwnerId

	// no validation rules for StartTime

	// no validation rules for Deadline

	// no validation rules for Status

	// no validation rules for Category

	// no validation rules for Permission

	if len(errors) > 0 {
		return CompetitionListResponse_CompetitionItemMultiError(errors)
	}

	return nil
}

// CompetitionListResponse_CompetitionItemMultiError is an error wrapping
// multiple validation errors returned by
// CompetitionListResponse_CompetitionItem.ValidateAll() if the designated
// constraints aren't met.
type CompetitionListResponse_CompetitionItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompetitionListResponse_CompetitionItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompetitionListResponse_CompetitionItemMultiError) AllErrors() []error { return m }

// CompetitionListResponse_CompetitionItemValidationError is the validation
// error returned by CompetitionListResponse_CompetitionItem.Validate if the
// designated constraints aren't met.
type CompetitionListResponse_CompetitionItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompetitionListResponse_CompetitionItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompetitionListResponse_CompetitionItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompetitionListResponse_CompetitionItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompetitionListResponse_CompetitionItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompetitionListResponse_CompetitionItemValidationError) ErrorName() string {
	return "CompetitionListResponse_CompetitionItemValidationError"
}

// Error satisfies the builtin error interface
func (e CompetitionListResponse_CompetitionItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompetitionListResponse_CompetitionItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompetitionListResponse_CompetitionItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompetitionListResponse_CompetitionItemValidationError{}
