// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: update_competition.proto

package admin

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCompetitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	StartTime  string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" binding:"required"`
	Deadline   string `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty" binding:"required"`
	Category   int32  `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	Permission int32  `protobuf:"varint,5,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *UpdateCompetitionRequest) Reset() {
	*x = UpdateCompetitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCompetitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionRequest) ProtoMessage() {}

func (x *UpdateCompetitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionRequest) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCompetitionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCompetitionRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateCompetitionRequest) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *UpdateCompetitionRequest) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *UpdateCompetitionRequest) GetPermission() int32 {
	if x != nil {
		return x.Permission
	}
	return 0
}

type UpdateCompetitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCompetitionResponse) Reset() {
	*x = UpdateCompetitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCompetitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompetitionResponse) ProtoMessage() {}

func (x *UpdateCompetitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompetitionResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompetitionResponse) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{1}
}

type AddQuestionToCptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids           []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty" binding:"required"`
	CompetitionId int32   `protobuf:"varint,2,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty" binding:"required"`
}

func (x *AddQuestionToCptRequest) Reset() {
	*x = AddQuestionToCptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionToCptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionToCptRequest) ProtoMessage() {}

func (x *AddQuestionToCptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionToCptRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionToCptRequest) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{2}
}

func (x *AddQuestionToCptRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *AddQuestionToCptRequest) GetCompetitionId() int32 {
	if x != nil {
		return x.CompetitionId
	}
	return 0
}

type AddQuestionToCptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddQuestionToCptResponse) Reset() {
	*x = AddQuestionToCptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQuestionToCptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionToCptResponse) ProtoMessage() {}

func (x *AddQuestionToCptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionToCptResponse.ProtoReflect.Descriptor instead.
func (*AddQuestionToCptResponse) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{3}
}

type ExcludeQuestionFromCptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompetitionId int32 `protobuf:"varint,1,opt,name=competition_id,json=competitionId,proto3" json:"competition_id,omitempty" form:"competition"`
	QuestionId    int32 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty" form:"question_id"`
}

func (x *ExcludeQuestionFromCptRequest) Reset() {
	*x = ExcludeQuestionFromCptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcludeQuestionFromCptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcludeQuestionFromCptRequest) ProtoMessage() {}

func (x *ExcludeQuestionFromCptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcludeQuestionFromCptRequest.ProtoReflect.Descriptor instead.
func (*ExcludeQuestionFromCptRequest) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{4}
}

func (x *ExcludeQuestionFromCptRequest) GetCompetitionId() int32 {
	if x != nil {
		return x.CompetitionId
	}
	return 0
}

func (x *ExcludeQuestionFromCptRequest) GetQuestionId() int32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type ExcludeQuestionFromCptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExcludeQuestionFromCptResponse) Reset() {
	*x = ExcludeQuestionFromCptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_update_competition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExcludeQuestionFromCptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExcludeQuestionFromCptResponse) ProtoMessage() {}

func (x *ExcludeQuestionFromCptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_competition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExcludeQuestionFromCptResponse.ProtoReflect.Descriptor instead.
func (*ExcludeQuestionFromCptResponse) Descriptor() ([]byte, []int) {
	return file_update_competition_proto_rawDescGZIP(), []int{5}
}

var File_update_competition_proto protoreflect.FileDescriptor

var file_update_competition_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x1a, 0x1f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x74,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e,
	0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0x9a, 0x84,
	0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x33, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x08, 0x64, 0x65, 0x61,
	0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x65,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x84,
	0x01, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f,
	0x43, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a,
	0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x43, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x99, 0x01, 0x0a, 0x1d, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e,
	0x03, 0x12, 0x66, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x66,
	0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x22, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x20, 0x0a,
	0x1e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x72, 0x6f, 0x6d, 0x43, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1c, 0x5a, 0x1a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_update_competition_proto_rawDescOnce sync.Once
	file_update_competition_proto_rawDescData = file_update_competition_proto_rawDesc
)

func file_update_competition_proto_rawDescGZIP() []byte {
	file_update_competition_proto_rawDescOnce.Do(func() {
		file_update_competition_proto_rawDescData = protoimpl.X.CompressGZIP(file_update_competition_proto_rawDescData)
	})
	return file_update_competition_proto_rawDescData
}

var file_update_competition_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_update_competition_proto_goTypes = []interface{}{
	(*UpdateCompetitionRequest)(nil),       // 0: admin.UpdateCompetitionRequest
	(*UpdateCompetitionResponse)(nil),      // 1: admin.UpdateCompetitionResponse
	(*AddQuestionToCptRequest)(nil),        // 2: admin.AddQuestionToCptRequest
	(*AddQuestionToCptResponse)(nil),       // 3: admin.AddQuestionToCptResponse
	(*ExcludeQuestionFromCptRequest)(nil),  // 4: admin.ExcludeQuestionFromCptRequest
	(*ExcludeQuestionFromCptResponse)(nil), // 5: admin.ExcludeQuestionFromCptResponse
}
var file_update_competition_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_competition_proto_init() }
func file_update_competition_proto_init() {
	if File_update_competition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_update_competition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCompetitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_update_competition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCompetitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_update_competition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionToCptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_update_competition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQuestionToCptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_update_competition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcludeQuestionFromCptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_update_competition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExcludeQuestionFromCptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_update_competition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_competition_proto_goTypes,
		DependencyIndexes: file_update_competition_proto_depIdxs,
		MessageInfos:      file_update_competition_proto_msgTypes,
	}.Build()
	File_update_competition_proto = out.File
	file_update_competition_proto_rawDesc = nil
	file_update_competition_proto_goTypes = nil
	file_update_competition_proto_depIdxs = nil
}
