// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: add_bank.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddBankRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddBankRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddBankRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddBankRequestMultiError,
// or nil if none found.
func (m *AddBankRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddBankRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Content

	if len(errors) > 0 {
		return AddBankRequestMultiError(errors)
	}

	return nil
}

// AddBankRequestMultiError is an error wrapping multiple validation errors
// returned by AddBankRequest.ValidateAll() if the designated constraints
// aren't met.
type AddBankRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddBankRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddBankRequestMultiError) AllErrors() []error { return m }

// AddBankRequestValidationError is the validation error returned by
// AddBankRequest.Validate if the designated constraints aren't met.
type AddBankRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddBankRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddBankRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddBankRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddBankRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddBankRequestValidationError) ErrorName() string { return "AddBankRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddBankRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddBankRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddBankRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddBankRequestValidationError{}

// Validate checks the field values on AddBankResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddBankResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddBankResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddBankResponseMultiError, or nil if none found.
func (m *AddBankResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddBankResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AddBankResponseMultiError(errors)
	}

	return nil
}

// AddBankResponseMultiError is an error wrapping multiple validation errors
// returned by AddBankResponse.ValidateAll() if the designated constraints
// aren't met.
type AddBankResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddBankResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddBankResponseMultiError) AllErrors() []error { return m }

// AddBankResponseValidationError is the validation error returned by
// AddBankResponse.Validate if the designated constraints aren't met.
type AddBankResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddBankResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddBankResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddBankResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddBankResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddBankResponseValidationError) ErrorName() string { return "AddBankResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddBankResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddBankResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddBankResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddBankResponseValidationError{}
